# Generated by Django 4.1.6 on 2023-02-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App12', '0002_remove_customer_id_remove_goods_id_remove_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='gid',
            new_name='gsid',
        ),
    ]
