# Generated by Django 4.1.6 on 2023-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App12', '0003_rename_gid_goods_gsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='gsid',
            new_name='gid',
        ),
    ]
