# Generated by Django 4.1.6 on 2023-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('salary', models.FloatField(default=0.0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('birthday', models.DateField(default=None)),
                ('born', models.CharField(max_length=30)),
                ('marries', models.BooleanField(default=False)),
            ],
        ),
    ]
